const mockFoodData = [
  {
    'id': '1',
    'name': 'Classic Burger',
    'description': 'Juicy beef patty with fresh lettuce, tomato, onion, pickles, and our special sauce on a toasted sesame bun.',
    'price': 299,
    'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    'category': 'Burger',
    'rating': 4.5,
    'reviewCount': 234,
    'ingredients': ['Beef patty', 'Lettuce', 'Tomato', 'Onion', 'Pickles', 'Special sauce', 'Sesame bun'],
    'preparationTime': 15,
    'calories': 650,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '2',
    'name': 'Margherita Pizza',
    'description': 'Traditional Italian pizza with fresh mozzarella, tomatoes, and basil on a crispy thin crust.',
    'price': 799,
    'imageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    'category': 'Pizza',
    'rating': 4.7,
    'reviewCount': 456,
    'ingredients': ['Pizza dough', 'Mozzarella', 'Tomatoes', 'Basil', 'Olive oil'],
    'preparationTime': 20,
    'calories': 800,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '3',
    'name': 'Chicken Alfredo Pasta',
    'description': 'Creamy fettuccine pasta with grilled chicken breast in our homemade alfredo sauce.',
    'price': 499,
    'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    'category': 'Pasta',
    'rating': 4.6,
    'reviewCount': 189,
    'ingredients': ['Fettuccine', 'Chicken breast', 'Heavy cream', 'Parmesan', 'Garlic', 'Butter'],
    'preparationTime': 25,
    'calories': 950,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '4',
    'name': 'Chocolate Lava Cake',
    'description': 'Decadent chocolate cake with a molten chocolate center, served with vanilla ice cream.',
    'price': 200,
    'imageUrl': 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
    'category': 'Dessert',
    'rating': 4.9,
    'reviewCount': 678,
    'ingredients': ['Dark chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour', 'Vanilla ice cream'],
    'preparationTime': 12,
    'calories': 420,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '5',
    'name': 'Fresh Mango Smoothie',
    'description': 'Refreshing blend of fresh mangoes, yogurt, and honey. Perfect for a hot day!',
    'price': 150,
    'imageUrl': 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800',
    'category': 'Drinks',
    'rating': 4.4,
    'reviewCount': 312,
    'ingredients': ['Fresh mango', 'Yogurt', 'Honey', 'Ice'],
    'preparationTime': 5,
    'calories': 220,
    'isPopular': false,
    'isAvailable': true
  },
  {
    'id': '6',
    'name': 'BBQ Bacon Burger',
    'description': 'Premium burger topped with crispy bacon, BBQ sauce, cheddar cheese, and onion rings.',
    'price': 999,
    'imageUrl': 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800',
    'category': 'Burger',
    'rating': 4.8,
    'reviewCount': 421,
    'ingredients': ['Beef patty', 'Bacon', 'Cheddar', 'BBQ sauce', 'Onion rings', 'Brioche bun'],
    'preparationTime': 18,
    'calories': 890,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '7',
    'name': 'Pepperoni Pizza',
    'description': 'Classic pizza loaded with mozzarella cheese and premium pepperoni slices.',
    'price': 1200,
    'imageUrl': 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800',
    'category': 'Pizza',
    'rating': 4.6,
    'reviewCount': 523,
    'ingredients': ['Pizza dough', 'Mozzarella', 'Pepperoni', 'Tomato sauce', 'Oregano'],
    'preparationTime': 20,
    'calories': 920,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '8',
    'name': 'Penne Arrabbiata',
    'description': 'Spicy Italian pasta with garlic, tomatoes, and red chili peppers in olive oil.',
    'price': 800,
    'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    'category': 'Pasta',
    'rating': 4.3,
    'reviewCount': 145,
    'ingredients': ['Penne pasta', 'Tomatoes', 'Garlic', 'Red chili', 'Olive oil', 'Parsley'],
    'preparationTime': 20,
    'calories': 550,
    'isPopular': false,
    'isAvailable': true
  },
  {
    'id': '9',
    'name': 'Tiramisu',
    'description': 'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
    'price': 400,
    'imageUrl': 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
    'category': 'Dessert',
    'rating': 4.7,
    'reviewCount': 389,
    'ingredients': ['Ladyfingers', 'Mascarpone', 'Espresso', 'Cocoa powder', 'Eggs', 'Sugar'],
    'preparationTime': 15,
    'calories': 380,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '10',
    'name': 'Strawberry Milkshake',
    'description': 'Thick and creamy milkshake made with fresh strawberries and vanilla ice cream.',
    'price': 345,
    'imageUrl': 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800',
    'category': 'Drinks',
    'rating': 4.5,
    'reviewCount': 267,
    'ingredients': ['Fresh strawberries', 'Vanilla ice cream', 'Milk', 'Whipped cream'],
    'preparationTime': 5,
    'calories': 340,
    'isPopular': false,
    'isAvailable': true
  },
  {
    'id': '11',
    'name': 'Veggie Burger',
    'description': 'Delicious plant-based patty with avocado, lettuce, tomato, and chipotle mayo.',
    'price': 680,
    'imageUrl': 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800',
    'category': 'Burger',
    'rating': 4.4,
    'reviewCount': 198,
    'ingredients': ['Veggie patty', 'Avocado', 'Lettuce', 'Tomato', 'Chipotle mayo', 'Whole wheat bun'],
    'preparationTime': 15,
    'calories': 480,
    'isPopular': false,
    'isAvailable': true
  },
  {
    'id': '12',
    'name': 'Hawaiian Pizza',
    'description': 'Tropical combination of ham, pineapple, and mozzarella on tomato sauce base.',
    'price': 1300,
    'imageUrl': 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    'category': 'Pizza',
    'rating': 4.2,
    'reviewCount': 334,
    'ingredients': ['Pizza dough', 'Mozzarella', 'Ham', 'Pineapple', 'Tomato sauce'],
    'preparationTime': 20,
    'calories': 850,
    'isPopular': false,
    'isAvailable': true
  },
  {
    'id': '13',
    'name': 'Carbonara Pasta',
    'description': 'Creamy pasta with crispy bacon, eggs, parmesan, and black pepper.',
    'price': 1399,
    'imageUrl': 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    'category': 'Pasta',
    'rating': 4.8,
    'reviewCount': 412,
    'ingredients': ['Spaghetti', 'Bacon', 'Eggs', 'Parmesan', 'Black pepper', 'Garlic'],
    'preparationTime': 20,
    'calories': 780,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '14',
    'name': 'New York Cheesecake',
    'description': 'Rich and creamy cheesecake with graham cracker crust and berry compote.',
    'price': 430,
    'imageUrl': 'https://images.unsplash.com/photo-1533134242820-b3b097e93bdf?w=800',
    'category': 'Dessert',
    'rating': 4.6,
    'reviewCount': 445,
    'ingredients': ['Cream cheese', 'Graham crackers', 'Sugar', 'Eggs', 'Vanilla', 'Berry compote'],
    'preparationTime': 15,
    'calories': 520,
    'isPopular': true,
    'isAvailable': true
  },
  {
    'id': '15',
    'name': 'Iced Coffee',
    'description': 'Refreshing cold brew coffee served over ice with a splash of cream.',
    'price': 170,
    'imageUrl': 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800',
    'category': 'Drinks',
    'rating': 4.3,
    'reviewCount': 289,
    'ingredients': ['Coffee beans', 'Ice', 'Cream', 'Sugar syrup'],
    'preparationTime': 3,
    'calories': 120,
    'isPopular': false,
    'isAvailable': true
  }
];